### ISSUE TITLE
npm install gives errors

### ISSUE THREAD

**Issue by orangejon** [aliargun/mcp-server-gemini#2]
Apologies if I'm installing it incorrectly but after cloning the repository, I get a lot of errors from npm when I try to install:

```
verbose stack Error: command failed
20 verbose stack     at promiseSpawn (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
20 verbose stack     at spawnWithShell (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
20 verbose stack     at promiseSpawn (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
20 verbose stack     at runScriptPkg (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
20 verbose stack     at runScript (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:12:10)
20 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:163:9)
20 verbose stack     at async Npm.exec (/usr/local/lib/node_modules/npm/lib/npm.js:207:9)
20 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli/entry.js:74:5)
21 verbose pkgid mcp-server-gemini@1.0.0
22 error code 2
23 error path /Users/jonathan/Documents/makuma-code/mcp-server-gemini
24 error command failed
25 error command sh -c npm run build
26 verbose cwd /Users/jonathan/Documents/makuma-code/mcp-server-gemini
27 verbose os Darwin 24.2.0
28 verbose node v23.5.0
29 verbose npm  v10.9.2
30 verbose exit 2
31 verbose code 2
```

I'm not sure what these errors mean or how to fix it?  Full log attached.

[2024-12-27T10_36_48_762Z-debug-0.log](https://github.com/user-attachments/files/18259727/2024-12-27T10_36_48_762Z-debug-0.log)

**Comment by orangejon** [comment]
I'm not sure if this is the same issue, but I followed your documentation to install it into Claude Desktop and I see that there is an npm command that runs briefly but then it exits and a "gemini disconnected" error appears in Claude Desktop. 

Screenshots attached. I also enabled debug mode but I don't know where to find the log file.

<img width="1112" alt="Screenshot 2024-12-27 at 13 31 30" src="https://github.com/user-attachments/assets/0875b4c2-d295-40c5-b871-64d0b1d4a3c8" />
<img width="1262" alt="Screenshot 2024-12-27 at 13 35 41" src="https://github.com/user-attachments/assets/fda8ee45-0b71-406a-b80c-a6b7d06e76a5" />
<img width="1112" alt="Screenshot 2024-12-27 at 13 27 32" src="https://github.com/user-attachments/assets/48e37a1a-c9b0-4b50-83bf-a9831e110aec" />

**Comment by aliargun** [comment]
I will check tomorrow and get back to you. Used ot today via this repo so dont know what is wrong with it of the top of my head

**Comment by davidlinse** [comment]
Hi, i'm facing the same issue. Any news on this ?
